# Generated by Django 5.2.14 on 2026-05-28 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('sport', models.CharField(max_length=100, verbose_name='deporte')),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('en_vivo', 'En vivo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('anulado', 'Anulado')], default='programado', max_length=20, verbose_name='estado')),
                ('starts_at', models.DateTimeField(verbose_name='inicia en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('market_type', models.CharField(choices=[('1X2', '1X2'), ('over_under', 'Over/Under'), ('btts', 'Both teams to score')], max_length=20, verbose_name='tipo')),
                ('status', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('suspendido', 'Suspendido'), ('liquidado', 'Liquidado')], default='abierto', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='betting.event', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'mercado',
                'verbose_name_plural': 'mercados',
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('odds', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='cuota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.market', verbose_name='mercado')),
            ],
            options={
                'verbose_name': 'seleccion',
                'verbose_name_plural': 'selecciones',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='monto apostado')),
                ('odds', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='cuota aceptada')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('settled_won', 'Settled won'), ('settled_lost', 'Settled lost'), ('cancelled', 'Cancelled')], default='accepted', max_length=20, verbose_name='estado')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='betting.market', verbose_name='mercado')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='betting.selection', verbose_name='seleccion')),
            ],
            options={
                'verbose_name': 'apuesta',
                'verbose_name_plural': 'apuestas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['event', 'status'], name='idx_market_event_status'),
        ),
        migrations.AddConstraint(
            model_name='selection',
            constraint=models.UniqueConstraint(fields=('market', 'name'), name='unique_selection_per_market'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'status'], name='idx_bet_user_status'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['market', 'status'], name='idx_bet_market_status'),
        ),
    ]
