# Generated by Django 5.2.14 on 2026-05-28 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccumulatedBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='monto total apostado')),
                ('combined_odds', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='cuota combinada')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('settled_won', 'Settled won'), ('settled_lost', 'Settled lost'), ('cancelled', 'Cancelled')], default='accepted', max_length=20, verbose_name='estado')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accumulated_bets', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'apuesta combinada',
                'verbose_name_plural': 'apuestas combinadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccumulatedBetLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds_at_bet', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='cuota al apostar')),
                ('settled', models.BooleanField(default=False, verbose_name='liquidado')),
                ('won', models.BooleanField(null=True, verbose_name='ganado')),
                ('accumulated_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='betting.accumulatedbet', verbose_name='apuesta combinada')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accumulator_legs', to='betting.market', verbose_name='mercado')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accumulator_legs', to='betting.selection', verbose_name='seleccion')),
            ],
            options={
                'verbose_name': 'pierna de combinada',
                'verbose_name_plural': 'piernas de combinadas',
            },
        ),
    ]
