# Generated by Django 5.2.14 on 2026-05-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_accumulatedbet_accumulatedbetleg'),
        ('betting', '0002_bet_ip_address'),
    ]

    operations = [
    ]
