# Generated by Django 5.2.14 on 2026-05-26 06:33

import apps.users.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('dni', models.CharField(max_length=9, unique=True, validators=[apps.users.validators.validate_dni], verbose_name='DNI')),
                ('first_name', models.CharField(max_length=30, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=30, verbose_name='apellidos')),
                ('birth_date', models.DateField(validators=[apps.users.validators.validate_mayoria_edad], verbose_name='fecha de nacimiento')),
                ('account_status', models.CharField(choices=[('pendiente_verificacion', 'Pendiente de verificación'), ('verificado', 'Verificado'), ('bloqueado', 'Bloqueado'), ('autoexcluido', 'Autoexcluido')], default='pendiente_verificacion', max_length=25, verbose_name='estado de cuenta')),
                ('deposit_limit_daily', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='límite diario de depósito')),
                ('deposit_limit_weekly', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='límite semanal de depósito')),
                ('deposit_limit_monthly', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='límite mensual de depósito')),
                ('deposit_limit_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='última modificación de límites')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='DepositLimitChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=30, verbose_name='campo modificado')),
                ('old_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='valor anterior')),
                ('new_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='valor nuevo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_changes', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'cambio de límite',
                'verbose_name_plural': 'cambios de límites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelfExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusion_type', models.CharField(choices=[('7_dias', '7 días'), ('30_dias', '30 días'), ('90_dias', '90 días'), ('indefinida', 'Indefinida')], max_length=15, verbose_name='tipo de exclusión')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_exclusions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'autoexclusión',
                'verbose_name_plural': 'autoexclusiones',
                'ordering': ['-created_at'],
            },
        ),
    ]
